# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd0c6cb18576a6985f2d2059a1daa60688f6b6bf30fb3e6b567a8acc156b0ce52518e4ed2a27c5a5e7778bce3d976e06a7425e2fbfdbf65dc51b9c6ccbb096d9

test:
  secret_key_base: ddfa5775a81b907042619cdb3dc8c6ae6937289f417c4710a354c0c89d20169a707918bab70f035e60299a172aecb75132181871693383489c023ee4a23af1cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
